export enum Region {
  BRAZIL = 'BR1',
  EUROPE_NORDIC_EAST = 'EUN1',
  EUROPE_WEST = 'EUW1',
  LATIN_AMERICA_NORTH = 'LA1',
  LATIN_AMERICA_SOUTH = 'LA2',
  NORTH_AMERICA = 'NA1',
  OCEANIA = 'OC1',
  RUSSIA = 'RU1',
  TURKEY = 'TR1',
  JAPAN = 'JP1',
  REPUBLIC_OF_KOREA = 'KR',
  PUBLIC_BETA_ENVIRONMENT = 'PBE'
}
